/**
 * FHIR Codes API
 * FHIR Codes API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: evlach@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Concept'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Concept'));
  } else {
    // Browser globals (root is window)
    if (!root.FhirCodesApi) {
      root.FhirCodesApi = {};
    }
    root.FhirCodesApi.ValueSet = factory(root.FhirCodesApi.ApiClient, root.FhirCodesApi.Concept);
  }
}(this, function(ApiClient, Concept) {
  'use strict';




  /**
   * The ValueSet model module.
   * @module model/ValueSet
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ValueSet</code>.
   * @alias module:model/ValueSet
   * @class
   * @param url {String} 
   */
  var exports = function(url) {
    var _this = this;

    _this['url'] = url;

  };

  /**
   * Constructs a <code>ValueSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValueSet} obj Optional instance to populate.
   * @return {module:model/ValueSet} The populated <code>ValueSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('concepts')) {
        obj['concepts'] = ApiClient.convertToType(data['concepts'], [Concept]);
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Array.<module:model/Concept>} concepts
   */
  exports.prototype['concepts'] = undefined;



  return exports;
}));


